### ISSUE TITLE
Quick Question on CHM13 compatibility

### ISSUE THREAD

**Issue by jamesdalg** [TheJacksonLaboratory/SvAnna#231]
Can SvAnna handle CHM13v2.0? From looking through read the docs, I don't see a specific way to run SVanna on the new (telomere to telomere) genome instead of hg38.

**Comment by ielis** [comment]
Hi @jamesdalg , 
unfortunately, SvAnna does not support CHM13v2.0, we only support hg38.

**Comment by pnrobinson** [comment]
The problem is that LIRICAL, and all of the other software like it that I know if, makes use of annotations made for hg38 (or hg19) and it would be extremely difficult to re-capitulate those annotations for new genome builds. For now, I think the new builds will be most useful to look for many classes of structural variation. For smaller variants, it is arguably defensible to continue to use hg38
