### ISSUE TITLE
homozygous and hemizygous SV

### ISSUE THREAD

**Issue by charliechen912ilovbash** [TheJacksonLaboratory/SvAnna#233]
Hi,
I'm wondering is there any difference when SvAnn annotating homozygous and hemizygous SV ?
Because, for example, homozygous deletion in a gene will probably cause loss of function,
but hemizygous deletion in a gene may not, since there is still one allele is functional.
In the paper, you mentioned "allelic depth to 5:5 when evaluating heterozygous SV, and 0:10 when evaluating homozygous or hemizygous SV", I would be appreciated if more details are provided.
Thank you.

**Comment by ielis** [comment]
Hi @charliechen912ilovbash,
> Because, for example, homozygous deletion in a gene will probably cause loss of function,
but hemizygous deletion in a gene may not, since there is still one allele is functional.

I'm not sure I'm following this. It only makes sense to talk about hemizygosity for variants called on gonosomes of a male sample. There may be some special cases (e.g. variants in the pseudoautosomal regions) but in general, a hemizygous variant (`1`) in a gene located on X or Y is likely a LoF, similarly to HOM ALT (`1/1`). 
Nevertheless, SvAnna does not consider the sex or the mode of inheritance. The PSV score is i) a function of the variant effect on the overlapping genomic elements, and b) phenotype. The score must be assessed in the context of the patient.

> In the paper, you mentioned "allelic depth to 5:5 when evaluating heterozygous SV, and 0:10 when evaluating homozygous or hemizygous SV.

Please note that the statement is in the performance benchmark section where we used simulations to estimate the performance. From this reason, we did not have actual read depths for the variants and we had to ensure that the read depth-based filtering does not remove the spike-in (variant).

**Comment by charliechen912ilovbash** [comment]
Thanks for reply and sorry for misunderstanding, I meant heterozygous SV, not hemizygous SV.
So, no matter the SV genotype is heterozygous or homozygous, SvAnn will annotate them in the same way ?

**Comment by ielis** [comment]
Yes, SvAnna does not take into account the genotype and the mode of inheritance of the disease(s) associated with the affected gene(s). If a gene is associated with >1 diseases, SvAnna uses the _max_ similarity between the patient's phenotype features and the disease.

**Comment by charliechen912ilovbash** [comment]
I understood, thank you very much!

May I ask another qustion without starting another issue:
Does SvAnn treat deletion with median size (e.g. 10 kb) and large size (e.g. 10 mb) in the same way? 

I am asking because some SV callers call an intra-chromosomal translocation as a large deletion (or a large inversion). If it is really a large deletion, then of course the genes within its region are deleted. But if it is actually an translocation, the genes within its region are not deleted. 
In such cases, tens of genes could be involved in a large SV.

**Comment by ielis** [comment]
> Does SvAnn treat deletion with median size (e.g. 10 kb) and large size (e.g. 10 mb) in the same way?

Yes, they're treated the same. Deletions should be called as deletions, inversions as inversions, etc., and it is the responsibility of the variant caller to provide correct variant types. Starting from a VCF file, SvAnna is in no position to question the validity of the variants, and the quality of the input data can make SvAnna more or less successful.

**Comment by charliechen912ilovbash** [comment]
I see, thanks very much!
